### ISSUE TITLE
Unclear whether numeric keys for structs are valid

### ISSUE THREAD

**Issue by R3D4C73D** [amznlabs/ion-tests#10]
There's currently no test data showing numeric keys for structs in either good or bad data.  The spec itself never addresses this.

This would be a useful feature for using structs as a form of sparse arrays.

**Comment by toddjonker** [comment]
Thanks for the feedback.  I think the spec covers this in the section on [structs](http://amznlabs.github.io/ion-docs/spec.html#struct):

> Structures are unordered collections of name/value pairs. The names are symbol tokens, and the values are unrestricted. 

Symbol tokens can have any Unicode content, including `'123'`, but that's not a number from the viewpoint of Ion.  In other words, `{ '123' : true }` is valid Ion data, but the field name isn't a number, as far as the data model is concerned.  We should make sure to have a test case the demonstrates that `{ 123 : true }` is invalid.

You probably don't want to representing sparse arrays using structs, since they are by definition unordered. I'd suggest trying something based on lists.
